root = "."
tmp_dir = "tmp"

[build]
  cmd = "swag init --dir .,internal/app --output docs && go build -o ./tmp/server ."
  bin = "./tmp/server"
  args_bin = ["--no-migrations"]
  include_ext = ["go"]
  exclude_dir = ["tmp", "docs"]

[log]
  time = true
